### ISSUE TITLE
better file conflicts

### ISSUE THREAD

**Issue by ekryski** [feathersjs-ecosystem/feathers-generator#2]
If a `force` option isn't passed and there is a file conflict we need to:
- tell the user that we have a conflict
- tell them which file is conflicting
- prompt for confirmation of overwrite
- write or ignore based on their answer

**Comment by slajax** [comment]
related to #27

**Comment by slajax** [comment]
@daffl @ekryski It looks like most of this functionality found in `generator-feathers` comes directly from the `yeoman-generator` APIs specifically `fs`. It *appears* that this even includes the conflict prompts, so since we're not using yeoman anymore, we'll need to hand role this as a custom metalsmith middleware that runs at the beginning of each generation (before things are copied, but after manifest is final) and validates the in-memory metalsmith file manifest against the actual file system. This might be a bit of a tricky race issue due to the `metalsmith-copy` and our rename middleware etc.
